title: Blogito, ergo sum
email: post@sebastiansemper.de
description: Mathe, Python, R, LaTeX, Musik, Geschichten und Philosophie
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sebastiansemper.github.io"
twitter_username: seb_sem
github_username:  sebastiansemper

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
